---
ui.level:                                   (advanced)
ui.nojs:                                    Oops! The interactive parts of <em>Classroom rocket scientist</em> need Javascript to be enabled. Sorry about that.
ui.title:                                   Classroom rocket scientist
ui.introduction:                            This is an intro.
ui.loading:                                 Loading space programme...
ui.requirements.title:                      Requirements
ui.button.type:                             Select this type
ui.button.goal:                             Select this mission
ui.button.zoomin:                           &plus;
ui.button.zoomout:                          &minus;
ui.button.threeD:                           2D/3D
ui.button.spin:                             Animate
ui.menu.title:                              Menu
ui.menu.restart.title:                      Restart
ui.menu.restart.more:                       Start over
ui.menu.units.title:                        Units
ui.menu.units.more:                         Change the units
ui.menu.level.title:                        Difficulty
ui.menu.level.more:                         Change the difficulty
ui.menu.fullscreen.title:                   Toggle fullscreen
ui.menu.fullscreen.more:                    Switch between viewing fullscreen or in a standard browser window
ui.menu.language.title:                     Language
ui.menu.language.more:                      Change language
ui.sections.type.short:                     Type
ui.sections.type.title:                     Select your type of satellite
ui.sections.type.intro:                     Satellites have different purposes. Which type do you want to build?
ui.sections.goal.short:                     Mission
ui.sections.goal.title:                     Select the purpose of your satellite
ui.sections.goal.intro:                     Select the purpose of your satellite
ui.sections.bus.short:                      Size
ui.sections.bus.title:                      Choose the size of your satellite
ui.sections.bus.intro:                      The size of your satellite matters. It needs to be big enough to hold all the instruments you need. Be careful though. The bigger your satellite, the more expensive it is.
ui.sections.bus.cost:                       Cost:
ui.sections.bus.mass:                       Mass:
ui.sections.bus.size:                       Size:
ui.sections.orbit.short:                    Orbit
ui.sections.orbit.title:                    Select the orbit for your satellite
ui.sections.orbit.intro:                    There are several different orbits around the Earth that you can choose from. Higher orbits need more powerful rockets to get to them.
ui.sections.orbit.list:                     Available orbits:
ui.sections.orbit.altitude:                 Altitude: 
ui.sections.orbit.period:                   Period: 
ui.sections.instrument.short:               Instruments
ui.sections.instrument.title:               Select the instruments for your satellite
ui.sections.instrument.intro:               To complete your mission you will need the correct instruments. You only have a limited number of slots and money so choose wisely.
ui.sections.instrument.list:                Available instruments:
ui.sections.power.short:                    Power
ui.sections.power.title:                    Add power
ui.sections.power.intro:                    Your satellite needs power. There are different ways to do that. You can use solar panels on the sides of the satellite, deployable solar panels, and batteries.
ui.sections.power.list:                     Available power devices:
ui.sections.rocket.short:                   Rocket
ui.sections.rocket.title:                   Build your rocket
ui.sections.rocket.intro:                   Now you have a satellite you need to build a multi-stage rocket. The top of the rocket will hold your satellite so needs to be big enough. The lower stages need to be big enough to support those above.
ui.sections.launch.short:                   Launch
ui.sections.launch.title:                   Launch
ui.sections.launch.intro:                   
bus.cube.title:                             Cube sat
bus.cube.button:                            Select cube sat
bus.small.title:                            Small satellite
bus.small.button:                           Select small satellite
bus.medium.title:                           Medium satellite
bus.medium.button:                          Select medium satellite
bus.large.title:                            Large satellite
bus.large.button:                           Select large satellite
package.camera-opt.title:                   Camera (optical)    # The title of the optical camera instrument
package.camera-opt.description:             Images of ground
package.camera-nir.title:                   Camera (NIR)
package.camera-nir.description:             Images of vegetation
package.camera-fir.title:                   Camera (FIR)
package.camera-fir.description:             Images of clouds
package.spect-opt.title:                    Spectrometer (optical)
package.spect-opt.description:              Properties of ground
package.spect-nir.title:                    Spectrometer (NIR)
package.spect-nir.description:              Properties of vegetation
package.spect-fir.title:                    Spectrometer (FIR)
package.spect-fir.description:              Properties of clouds
package.radar-alt.title:                    Radar altimeter
package.radar-alt.description:              Measuring topography
package.radar-alt.requires.dish.label:      Requires a radar dish
package.radar-alt.requires.dish.error:      You need to include a radar dish for the altimeter to work
package.radar-dish.title:                   Radar dish
package.radar-dish.description:             Measuring topography
package.radio-rx.title:                     Radio receiver
package.radio-rx.description:               Communications
package.radio-tx.title:                     Radio transmitter
package.radio-tx.description:               Communications
package.atomic-clock.title:                 Atomic clock
package.atomic-clock.description:           Navigation (GPS timing)
package.atomic-clock-small.title:           Atomic clock (compact)
package.atomic-clock-small.description:     Navigation (GPS timing)
package.gps-rx.title:                       GPS receiver (miniature)
package.gps-rx.description:                 Positioning
package.camera-mini.title:                  Camera (miniature)
package.camera-mini.description:            Images of ground
package.dish-large.title:                   Radio dish (large)
package.dish-large.description:             For up to 8 instruments
package.dish-medium.title:                  Radio dish
package.dish-medium.description:            For up to 4 instruments
package.dish-small.title:                   Radio antenna (compact)
package.dish-small.description:             For up to 2 instruments
package.radio-antenna-cube.title:           Radio antenna (deployable)
package.radio-antenna-cube.description:     For up to 2 instruments
package.battery-large.title:                Large battery
package.battery-large.description:          Provides power
package.battery-large.requires.solar.label: Requires solar panels
package.battery-large.requires.solar.error: Requires solar panels
package.battery-small.title:                Small battery
package.battery-small.description:          Provides power
package.battery-small.requires.solar.label: Requires solar panels
package.battery-small.requires.solar.error: Requires solar panels
package.rtg.title:                          RTG
package.rtg.description:                    Provides power
package.rtg.requires.orbit.label:           Not for low-Earth orbit
package.rtg.requires.orbit.error:           Can't use an RTG in low-Earth orbit
package.solar-panel-surface.title:          Body-mounted solar panel
package.solar-panel-surface.description:    Provides power
package.solar-panel.title:                  Deployable solar panel
package.solar-panel.description:            Provides power
orbit.LEO.title:                            Low-Earth orbit
orbit.LEO.description:                      A description
orbit.MEO.title:                            Medium-Earth orbit
orbit.MEO.description:                      A description
orbit.HEO.title:                            Highly-elliptical orbit
orbit.HEO.description:                      A description
orbit.GEO.title:                            Geo-stationary orbit
orbit.GEO.description:                      A description
scenarios.NAV.title:                        Navigation
scenarios.NAV.description:                  The global positioning system is made up of 24 satellites that orbit at an altitude of <span data-dimension="length" data-units="km" data-value="20000" class="value convertable">20,000 km</span> above the surface of the Earth. The difference in time for signals received from four satellites is used to calculate the exact location of a GPS receiver on Earth.
scenarios.COMMS.title:                      Communication
scenarios.COMMS.description:                These are used for television, phone or internet transmissions, for example, the Optus D1 satellite is in a geostationary orbit above the equator and has a coverage footprint to provide signals to all of Australia and New Zealand.
scenarios.EO.title:                         Earth observation
scenarios.EO.description:                   These are used to image clouds and measure temperature and rainfall. Both geostationary and low Earth orbits are used depending on the type of weather satellite. Weather satellites are used to help with more accurate weather forecasting. These are used to photograph and image the Earth. Low Earth orbits are mainly used so that more detailed images can be produced.
...