---
ui.nojs:                                    Oops! If you're seeing this it looks as though there's a problem which is preventing Classroom Rocket Scientist from working. It requires Javascript to be enabled (but does not require Flash or Java plugins). You can use the <a href="http://www.whatsmybrowser.org/">"What's my browser"</a> website to find out what browser version you're using, and whether Javascript is enabled.
ui.title:                                   Classroom rocket scientist
ui.loading:                                 Loading...
ui.menu.restart.title:                      Restart
ui.menu.restart.more:                       Start over
ui.menu.units.title:                        Units
ui.menu.units.more:                         Change the units
ui.menu.level.title:                        Difficulty
ui.menu.level.more:                         Change the difficulty
ui.menu.fullscreen.title:                   Toggle fullscreen
ui.menu.fullscreen.more:                    Switch between viewing fullscreen or in a standard browser window
ui.menu.language.title:                     Language
ui.menu.language.more:                      Change language
ui.sections.type.title:                     Select your type of satellite
ui.sections.goal.title:                     Select the purpose of your satellite
ui.sections.bus.title:                      Choose the size of your satellite
ui.sections.orbit.title:                    Select the orbit for your satellite
ui.sections.instrument.title:               Select the instruments for your satellite
ui.sections.power.title:                    Add power
ui.sections.rocket.title:                   Build your rocket
ui.sections.launch.title:                   Launch
package.camera-opt.title:                   Camera (optical)    # The title of the optical camera instrument
package.camera-opt.description:             Images of ground
package.camera-nir.title:                   Camera (NIR)
package.camera-nir.description:             Images of vegetation
package.camera-fir.title:                   Camera (FIR)
package.camera-fir.description:             Images of clouds
package.spect-opt.title:                    Spectrometer (optical)
package.spect-opt.description:              Properties of ground
package.spect-nir.title:                    Spectrometer (NIR)
package.spect-nir.description:              Properties of vegetation
package.spect-fir.title:                    Spectrometer (FIR)
package.spect-fir.description:              Properties of clouds
package.radar-alt.title:                    Radar altimeter
package.radar-alt.description:              Measuring topography
package.radar-alt.requires.dish.label:      Requires a radar dish
package.radar-alt.requires.dish.error:      You need to include a radar dish for the altimeter to work
package.radar-dish.title:                   Radar dish
package.radar-dish.description:             Measuring topography
package.radio-rx.title:                     Radio receiver
package.radio-rx.description:               Communications
package.radio-tx.title:                     Radio transmitter
package.radio-tx.description:               Communications
package.atomic-clock.title:                 Atomic clock
package.atomic-clock.description:           Navigation (GPS timing)
package.atomic-clock-small.title:           Atomic clock (compact)
package.atomic-clock-small.description:     Navigation (GPS timing)
package.gps-rx.title:                       GPS receiver
package.gps-rx.description:                 Positioning
package.camera-mini.title:                  Camera (miniature)
package.camera-mini.description:            Images of ground
package.dish-large.title:                   Radio dish (large)
package.dish-large.description:             For up to 8 instruments
package.dish-medium.title:                  Radio dish (medium)
package.dish-medium.description:            For up to 4 instruments
package.dish-small.title:                   Radio antenna (small)
package.dish-small.description:             For up to 2 instruments
package.antenna-cube.title:                 Radio antenna (deployable)
package.antenna-cube.description:           For up to 2 instruments
package.battery-large.title:                Large battery
package.battery-large.description:          Provides power
package.battery-small.title:                Small battery
package.battery-small.description:          Provides power
package.battery-small.requires.solar.label: Requires solar panels
package.battery-small.requires.solar.error: Requires solar panels
package.rtg.title:                          RTG
package.rtg.description:                    Provides power
package.rtg.requires.orbit.label:           Not for low-Earth orbit
package.rtg.requires.orbit.error:           Can't use an RTG in low-Earth orbit
package.solar-panel-surface.title:          Body-mounted solar panel
package.solar-panel-surface.description:    Provides power
package.solar-panel.title:                  Deployable solar panel
package.solar-panel.description:            Provides power
scenario.NAV.title:                         Navigation satellite
scenario.NAV.description:                   The global positioning system is made up of 24 satellites that orbit at an altitude of <span data-dimension="length" data-units="km" data-value="20000" class="value convertable">20,000 km</span> above the surface of the Earth. The difference in time for signals received from four satellites is used to calculate the exact location of a GPS receiver on Earth.
scenario.COMMS.title:                       Communication satellite
scenario.COMMS.description:                 These are used for television, phone or internet transmissions, for example, the Optus D1 satellite is in a geostationary orbit above the equator and has a coverage footprint to provide signals to all of Australia and New Zealand.
scenario.EO.title:                          Earth observation satellite
scenario.EO.description:                    These are used to image clouds and measure temperature and rainfall. Both geostationary and low Earth orbits are used depending on the type of weather satellite. Weather satellites are used to help with more accurate weather forecasting. These are used to photograph and image the Earth. Low Earth orbits are mainly used so that a more detailed images can be produced.
...