---
ui.level:                                   (advanced)
ui.level.beginner:                          Beginner (ages 7-11)
ui.level.intermediate:                      Intermediate (ages 9-11)
ui.level.advanced:                          Advanced (ages 11-14)
ui.nojs:                                    Oops! The interactive parts of <em>Classroom rocket scientist</em> need Javascript to be enabled. Sorry about that.
ui.title:                                   Classroom rocket scientist
ui.introduction:                            This is an intro.
ui.loading:                                 Loading space programme...
ui.requirements.title:                      Requirements
ui.button.type:                             Select this type
ui.button.goal:                             Select this mission
ui.button.zoomin:                           &plus;
ui.button.zoomout:                          &minus;
ui.button.threeD:                           2D/3D
ui.button.spin:                             Animate
ui.menu.title:                              Menu
ui.menu.restart.title:                      Restart
ui.menu.restart.more:                       Start over
ui.menu.units.title:                        Units
ui.menu.units.more:                         Change the units
ui.menu.level.title:                        Difficulty
ui.menu.level.more:                         Change the difficulty
ui.menu.fullscreen.title:                   Toggle fullscreen
ui.menu.fullscreen.more:                    Switch between viewing fullscreen or in a standard browser window
ui.menu.language.title:                     Language
ui.menu.language.more:                      Change language
ui.sections.type.short:                     Type
ui.sections.type.title:                     Select your type of satellite
ui.sections.type.intro:                     Satellites have different purposes. Which type do you want to build?
ui.sections.goal.short:                     Mission
ui.sections.goal.title:                     Select the purpose of your satellite
ui.sections.goal.intro:                     Make sure to take a note of the budget you have. You will need to make sure you don't overspend.
ui.sections.bus.short:                      Size
ui.sections.bus.title:                      Choose the size of your satellite
ui.sections.bus.intro:                      The size of your satellite matters. It needs to be big enough to hold all the instruments you need. Be careful though. The bigger your satellite, the more expensive it is.
ui.sections.bus.type:                       Type:
ui.sections.bus.cost:                       Structure cost:
ui.sections.bus.mass:                       Payload mass:
ui.sections.bus.structure:                  Structure mass:
ui.sections.bus.size:                       Structure size:
ui.sections.orbit.short:                    Orbit
ui.sections.orbit.title:                    Select the orbit for your satellite
ui.sections.orbit.intro:                    There are several different orbits around the Earth that you can choose from. Higher orbits need more powerful rockets to get to them.
ui.sections.orbit.list:                     Available orbits:
ui.sections.orbit.altitude:                 Altitude:
ui.sections.orbit.period:                   Period:
ui.sections.instrument.short:               Instruments
ui.sections.instrument.title:               Select the instruments for your satellite
ui.sections.instrument.intro:               To complete your mission you will need the correct instruments. You only have a limited number of slots and money so choose wisely.
ui.sections.instrument.list:                Available instruments:
ui.sections.power.short:                    Power
ui.sections.power.title:                    Add power
ui.sections.power.intro:                    Your satellite needs power. There are different ways to do that. You can use solar panels on the sides of the satellite, deployable solar panels, and batteries.
ui.sections.power.list:                     Available power devices:
ui.sections.rocket.short:                   Rocket
ui.sections.rocket.title:                   Build your rocket
ui.sections.rocket.intro:                   Now you have a satellite you need to build a multi-stage rocket. The top of the rocket will hold your satellite so needs to be big enough. The lower stages need to be big enough to support those above.
ui.sections.launch.short:                   Launch
ui.sections.launch.title:                   Ready to launch?
ui.sections.launch.checklist:               We've detected problems with your mission. These should be fixed before trying to launch or your mission will fail.
ui.sections.launch.goforlaunch:             Final checks have shown that your mission is within budget, you have a suitable rocket, and you have a satellite that will achieve your goals. Mission Control is waiting for you to give the OK.
ui.sections.launch.button:                  Go for launch!
bus.cube.title:                             Cube sat
bus.cube.button:                            Select cube sat
bus.small.title:                            Small satellite
bus.small.button:                           Select small satellite
bus.medium.title:                           Medium satellite
bus.medium.button:                          Select medium satellite
bus.large.title:                            Large satellite
bus.large.button:                           Select large satellite
package.camera-opt.title:                   Optical camera    # The title of the optical camera instrument
package.camera-opt.description:             Provides images of the ground, such as for mapping or for monitoring natural disasters. Can also be used to monitor cloud cover. The resolution depends on the orbit altitude.
package.camera-opt-hires.title:             High-resolution optical camera
package.camera-opt-hires.description:       Provides very high-resolution images of the ground, such as for monitoring natural disasters, but only when used in low-Earth orbit.
package.camera-nir.title:                   Vegetation camera
package.camera-nir.description:             Provides infrared images of vegetation and land-usage on the ground. Only works in daylight, as it relies on reflected sunlight.
package.camera-fir.title:                   Atmospheric camera
package.camera-fir.description:             Provides infrared images of the clouds and weather systems in the Earth's atmosphere, useful for weather forecasting and climate monitoring, even during darkness.
package.spect-opt.title:                    Optical Spectrometer
package.spect-opt.description:              Measures detailed properties of the Earth's surface, such as deforestation.
package.spect-nir.title:                    Vegetation Spectrometer
package.spect-nir.description:              Measures the properties of vegetation on the ground, such type of vegetation and how healthy it is.
package.spect-fir.title:                    Atmospheric Spectrometer
package.spect-fir.description:              Uses infrared light to measure properties of the Earth's atmosphere, such as clouds, moisture level, surface temperature and air temperature, even during darkness.
package.radar-alt.title:                    Radar altimeter
package.radar-alt.description:              Uses radio waves to measure the height of the ground, or topography, in very high resolution. Can be used to map the surface, or provide information on the effect of earthquakes.
package.radar-alt.requires.dish.label:      Requires a radar dish
package.radar-alt.requires.dish.error:      You need to include a radar dish for the altimeter to work
package.radar-dish.title:                   Radar dish
package.radar-dish.description:             Transmits and receives radio waves for the radar altimeter
package.radio-rx.title:                     Radio receiver
package.radio-rx.description:               Receives instructions from the ground control team
package.radio-tx.title:                     Radio transmitter
package.radio-tx.description:               Transmits information collected by the satellite to the ground
package.atomic-clock.title:                 Atomic clock
package.atomic-clock.description:           Very accurate clock, required by navigation satellites to measure the time to very high precision.
package.atomic-clock-small.title:           Atomic clock (compact)
package.atomic-clock-small.description:     Very accurate clock, required by navigation satellites to measure the time to very high precision.
package.gps-rx.title:                       GPS receiver (miniature)
package.gps-rx.description:                 Used to monitor the satellite's position to very high accuracy
package.camera-mini.title:                  Camera (miniature)
package.camera-mini.description:            Takes images of the ground
package.dish-large.title:                   Radio dish (large)
package.dish-large.description:             Radio dish capable of controlling and transmitting images & data from up to 8 instruments
package.dish-medium.title:                  Radio dish
package.dish-medium.description:            Radio dish capable of controlling and transmitting images & data from up to 4 instruments
package.dish-small.title:                   Radio antenna (compact)
package.dish-small.description:             Radio dish capable of controlling and transmitting images & data from up to 2 instruments
package.radio-antenna-cube.title:           Radio antenna (deployable)
package.radio-antenna-cube.description:     Deployable radio antenna capable of controlling and transmitting images & data from up to 2 instruments
package.battery-large.title:                Large battery
package.battery-large.description:          Stores power from solar panels to allow operation when not in sunlight
package.battery-large.requires.solar.label: Requires solar panels to charge up
package.battery-large.requires.solar.error: Requires solar panels
package.battery-small.title:                Small battery
package.battery-small.description:          Stores power from solar panels to allow operation when not in sunlight
package.battery-small.requires.solar.label: Requires solar panels
package.battery-small.requires.solar.error: Requires solar panels
package.rtg.title:                          RTG
package.rtg.description:                    A "Radioisotope Thermal Generator" uses nuclear technology to provide power. Due to safety concerns, it can't be used in low-Earth orbit.
package.rtg.requires.orbit.label:           Not for low-Earth orbit
package.rtg.requires.orbit.error:           Can't use an RTG in low-Earth orbit
package.solar-panel-surface.title:          Body-mounted solar panel
package.solar-panel-surface.description:    Solar panels mounted onto surface of satellite, collecting sunlight to provide power. Can power instruments, or charge up batteries.
package.solar-panel.title:                  Deployable solar panel
package.solar-panel.description:            Solar panels deployed from edge of satellite, collecting sunlight to provide power. Can power instruments, or charge up batteries.
orbit.LEO.title:                            Low-Earth orbit
orbit.LEO.description:                      Satellites in low-Earth orbit pass over a different part of the Earth in each orbit. It is cheaper to send satellites to Low-Earth orbit than other orbits and satellites here can be reached for repairs. Low-Earth orbit satellites can look at small areas in high detail for short periods of time.
orbit.MEO.title:                            Medium-Earth orbit
orbit.MEO.description:                      Satellites in medium-Earth orbit are higher above the Earth than low-Earth orbits, but lower than geostationary orbits. They cover a different part of Earth in each orbit. They can see a larger area in less detail than low-Earth orbits.
orbit.HEO.title:                            Highly-elliptical orbit
orbit.HEO.description:                      Highly-elliptical orbits are much closer to the Earth at one point in their orbit (called perigee) than another (called apogee), giving an elliptical rather than circular orbit. Due to Kepler's laws, they spend most of their time at apogee, above one area of Earth than another at perigee. They are useful for covering areas including high latitudes. More than one satellite can be used for continuous coverage of an area.
orbit.GEO.title:                            Geo-stationary orbit
orbit.GEO.description:                      Satellites in geostationary orbits orbit at the same speed as the Earth spins, so stay above the same location on Earth near the equator and complete a full orbit in 24 hours. They are much higher above the Earth's surface than other orbits, so can see the entire hemisphere in less detail.
scenarios.NAV.title:                        Navigation Satellite
scenarios.NAV.description:                  The global positioning system is made up of 24 satellites that orbit at an altitude of <span data-dimension="length" data-units="km" data-value="20000" class="value convertable">20,000 km</span> above the surface of the Earth. The difference in time for signals received from four satellites is used to calculate the exact location of a GPS receiver on Earth.
scenarios.NAV.sat-nav.title:                Satellite Navigation System
scenarios.NAV.sat-nav.description:          Uses signals from four navigation satellites so satnav users can find their location on Earth.
scenarios.NAV.sat-nav.req.atomic.label:     Measures time accurately
scenarios.NAV.sat-nav.req.atomic.error:      You are not able to measure the time accurately enough.
scenarios.COMMS.title:                      Communication Satellite
scenarios.COMMS.description:                These are used for television, phone or internet transmissions, for example, the Optus D1 satellite is in a geostationary orbit above the equator and has a coverage footprint to provide signals to all of Australia and New Zealand.
scenarios.EO.title:                         Earth Observation Satellite
scenarios.EO.description:                   These are used to image clouds and measure temperature and rainfall. Both geostationary and low Earth orbits are used depending on the type of weather satellite. Weather satellites are used to help with more accurate weather forecasting. These are used to photograph and image the Earth. Low Earth orbits are mainly used so that more detailed images can be produced.
---